#!/bin/bash
clear
# Ask the employee for their name
echo "Welcome to New Employee!"
echo Please Enter Employee Name 
read varName
echo Thank you $varName
echo Please Enter Employee Pay
 read varPay
echo $varName          $varPay >> payroll.txt
